version: "3.8"
services: 
  mongodb:
    image: "mongo"
    # container_name: mongodb
    volumes: 
      - goals-data:/data/db
    # environment: 
      # MONGO_INITDB_ROOT_USERNAME: admin
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=test1
    env_file: 
      - ./env/mongo.env
    # networks: 
    #   - goals-net
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile-dev
    ports: 
      - "80:80"
    volumes: 
      - goals-log:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on: 
      - mongodb
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend
volumes: 
  goals-data:
  goals-log: