apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: pedropicateclas/kub-demo-users:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: AUTH_ADDRESS
              #value: localhost # <- use localhost for internal pods communications
              value: "auth-service.default" #default comes from namespaces
          # ports:
          # - containerPort: <Port>
